services:
  - type: web
    name: n8n-flower-order-system
    env: docker
    plan: free
    repo: https://github.com/Maggie-SJP/flower-order-system
    branch: main
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_HOST
        value: n8n-flower-order-system.onrender.com
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://n8n-flower-order-system.onrender.com
      - key: GENERIC_TIMEZONE
        value: Australia/Brisbane
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: your-username   # <<== 改成你想設的帳號
      - key: N8N_BASIC_AUTH_PASSWORD
        value: your-password   # <<== 改成你想設的密碼

      # PostgreSQL 連線設定
      - key: DB_TYPE
        value: postgres
      - key: DB_POSTGRESDB_HOST
        value: dpg-d23epn2dbo4c7385a96g-a
      - key: DB_POSTGRESDB_PORT
        value: 5432
      - key: DB_POSTGRESDB_DATABASE
        value: n8n_flower_order_db
      - key: DB_POSTGRESDB_USER
        value: n8n_flower_order_db_user
      - key: DB_POSTGRESDB_PASSWORD
        value: 2uQzeWYm4PO2V3p0RjwLkmATqwtdpwnF
