services:
  - type: web
    name: n8n-flower-order-system
    env: docker
    repo: https://github.com/Maggie-SJP/flower-order-system
    branch: main
    dockerfilePath: ./docker/Dockerfile
    envVars:
      - key: DB_TYPE
        value: postgresdb

      - key: DB_POSTGRES_HOST
        value: dpg-d23epn2dbo4c7385a96g-a
      - key: DB_POSTGRES_PORT
        value: 5432
      - key: DB_POSTGRES_DATABASE
        value: n8n_flower_order_db
      - key: DB_POSTGRES_USER
        value: n8n_flower_order_db_user
      - key: DB_POSTGRES_PASSWORD
        value: 2uQzeWYm4PO2V3p0RjwLkmATqwtdpwnF

      - key: GENERIC_TIMEZONE
        value: Australia/Brisbane

      - key: N8N_HOST
        value: n8n-flower-order-system.onrender.com
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https

      # 若未來需要保護介面登入，請再加入以下這些（可選）：
      # - key: N8N_BASIC_AUTH_ACTIVE
      #   value: "true"
      # - key: N8N_BASIC_AUTH_USER
      #   value: your_username
      # - key: N8N_BASIC_AUTH_PASSWORD
      #   value: your_password
      # - key: N8N_ENCRYPTION_KEY
      #   value: a_secure_generated_key
