services:
  - type: web
    name: n8n-flower-order-system
    env: docker
    repo: https://github.com/Maggie-SJP/flower-order-system
    branch: main
    dockerfilePath: ./docker/Dockerfile
    envVars:
      - key: DB_TYPE
        value: postgres
      - key: DB_POSTGRESDB_HOST
        value: dpg-d23epn2dbo4c7385a96g-a
      - key: DB_POSTGRESDB_PORT
        value: 5432
      - key: DB_POSTGRESDB_DATABASE
        value: n8n_flower_order_db
      - key: DB_POSTGRESDB_USER
        value: n8n_flower_order_db_user
      - key: DB_POSTGRESDB_PASSWORD
        value: 2uQzeWYm4PO2V3p0RjwLkmATqwtdpwnF
      - key: GENERIC_TIMEZONE
        value: Australia/Brisbane
      - key: N8N_HOST
        value: n8n-flower-order-system.onrender.com
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
